### ISSUE TITLE
explain shouldnt be private

### ISSUE THREAD

**Issue by rauhs** [siilisolutions/humanize#5]
I think explain shouldnt be private. Not everybody is dealing with exceptions.

**Comment by esuomi** [comment]
Yeah that got lost somewhere along the line. `s/check` support is..."whoopsied" at the moment :) I'll have a look at that soonish, I hope to have some time to do some coding this weekend.

**Comment by esuomi** [comment]
Hi!

So my week is about 20 days, but this is now fixed in v0.1.1
